variables:
  PORT: 5022
  #                USER@SERVER
  DEST_SERVER: "jenkins@10.11.103.27"
  DEST_PATH: /var/www/html/passport

stages:
  #      - build
  #      - test
  - deploy_composer
  - deploy_files
  - deploy_migrate

#deploy_job1:
#  artifacts:
#      paths:
#      - build/
# only:
# - master

composer_install:
  only:
    - master
  stage: deploy_composer
  script:
    - scp -P $PORT composer.{json,lock} $DEST_SERVER:$DEST_PATH
    # Makes the server print the executed commands to stdout.
    # Required for monitoring and debug.
    - ssh -p$PORT $DEST_SERVER "set -x &&cd $DEST_PATH &&composer install"

deploy_files:
  only:
    - master
  stage: deploy_files
  script:
    - EXCLUDE={'.git*','rsync.log','vendor/',
    - EXCLUDE+='rbac/assignments.php','runtime/','.env',
    - EXCLUDE+='web/assets/','web/uploads/',
    - EXCLUDE+='commands/private/'}
    - '[ -f rsync.log ]&& rm rsync.log'
    - echo $EXCLUDE
    - >
      eval rsync -rl --del -e \'ssh -p $PORT\'  --exclude=$EXCLUDE ./
      $DEST_SERVER:$DEST_PATH --log-file=rsync.log

run_migrate:
  only:
    - master
  stage: deploy_migrate
  script:
    - >
      ssh -p$PORT $DEST_SERVER "set -x && /usr/bin/php $DEST_PATH/yii
      migrate --interactive=0 2>&1> $DEST_PATH/runtime/logs/migrate2.log"
